MAX_STEPS = 50
MAX_POSITIONS = 52
MAX_PLAYERS = 4
MAX_PIECES = 4
MAX_FINISH_LANE_POSITIONS = 6


PRINT_EVENTS = False
PRINT_PIECE_FINISHES = False
PRINT_PIECES_MOVED_FROM_HOME = False
PRINT_WINNER = False
PRINT_NO_MOVE = False